### ISSUE TITLE
李哥你好，请问xmap可以像masscan一样编译成一个单文件然后别的机器不需要编译即可使用呢？

### ISSUE THREAD

**Issue by 759071793** [idealeer/xmap#12]
李哥你好，请问xmap可以像masscan一样编译成一个单文件然后别的机器不需要编译即可使用呢？

**Comment by idealeer** [comment]
可以的，可以copy出来试一试

**Comment by 759071793** [comment]
我其实对linux不是很懂，我在机器上编译好，安装后需要每次用sudo才能运行，可不可以麻烦给一份示例，我具体都还不知道怎么下手。编译好的文件，我找了好多目录都没有找到。。
我使用了masscan对比xmap，xmap真的太强大了，扫描一个ipv6/32瞬间就可以完成。

**Comment by 759071793** [comment]
找到了，/usr/local/sbin/xmap，这个文件我直接复制出来就可以了哇？我试试

**Comment by 759071793** [comment]
成功了，原来是我编译的时候是debian11，复制到centos时，库不一样，复制到相同系统的debian11下就可以了
