### ISSUE TITLE
最近两天非常不好用了，扫描失败率增加一半以上，还扫描了很多不通的端口

### ISSUE THREAD

**Issue by 759071793** [idealeer/xmap#13]
使用xmap很久了，昨天开始扫描ipv4端口不好用了，使用masscan 10000 RATE 扫描ASN 140096网段的端口可以扫到六百多个存活443端口。
但是用xmap用10000 RATE 只能扫描到三百多个，如果将RATE调到500.则会扫到很多443根本不通的ip保存下载，我用的配置如下：
masscan配置：
`./masscan -p 443 -iL asn/140096-ipv4 --wait=3 --rate=10000 -oL data1.txt --interface WARP`
xmap配置：
`./xmap -4 -p 443 -w asn/140096-ipv4 -x 32 -R 10000 -M tcp_syn -i WARP -X -o data.txt`

**Comment by idealeer** [comment]
哈喽，请问下你使用的是哪个版本？多次扫描都是这样吗？

**Comment by 759071793** [comment]
> 哈喽，请问下你使用的是哪个版本？多次扫描都是这样吗？

谢谢李哥回复，我使用的是master分支全新编译的，多次测试都是这种结果。我自己写了一个项目测试cloudflare的中转ip，最近勇xmap扫描到的443端口发现45102中转的cloudflareip变少了，然后我用masscan测试却依旧很多，所以排查data.txt文件发现扫描到的ip发现异常，里面我随机挑选一些ip单独测试端口很多443不通，但是用masscan扫描的话就是没有问题的，特此来反馈下。
对了，我的vps上安装了cloudflare warp vpn，所以指定了网卡为warp

**Comment by 759071793** [comment]
> 哈喽，请问下你使用的是哪个版本？多次扫描都是这样吗？

如果需要的话，我把我的vps环境发给您测试下吗，刚刚我又测试了一下，还是一样的结果。

**Comment by idealeer** [comment]
大概了解了，使用了 cf 的 vpn 虚拟网卡，这个之前确实没有做过测试。之前的测试也是用的 warp 网卡吗

**Comment by 759071793** [comment]
> 

最开始是没有使用warp虚拟网卡一切正常，但是如果长期用原生ip去扫描一些特定网段vps会被警告，上次就被韩国的一个运营商投诉到vps商家那里去了，后面才启用的warp，后面用warp后用了一段时间也没有问题，因为我每两天会扫一次固定asn网段的端口，然后持续用了warp大概几周后，三天前就发现有一些不对劲了，然后才编译了一个类似的产品masscan，发现masscan却没有问题，特此来请教。

**Comment by GeekerYT** [comment]
你好，我也有类似的问题：
src/xmap -i eth1 -x 48 -U rand -B 1M -G 2c:21:72:eb:47:f0 2405:200::/32
发现没有任何回应

**Comment by idealeer** [comment]
感谢反馈，我这边会做点测试。
没有任何回应的话，本地mac，网关mac等网络配置可以再检查检查，以及调用的模块。

**Comment by bilibilipala** [comment]
你好，想向你咨询一个问题，我是使用Cloudflare WARP 一键安装脚本部署的warp服务，我自己测试了一下，发现masscan使用warp的网卡不能返回端口开放的数据，`sudo masscan -p53 -i wgcf 8.8.8.8`这是我的命令，想请问下您是怎么配置的warp？我查询了一些资料，有人说warp是基于Wire­Guard模式，而这个工具只支持UDP形式的包，所以这就让我更困惑了，希望能得到回复

**Comment by bilibilipala** [comment]
我最近也在用CF warp做一些端口扫描，看到你的这个问题之后我开始使用masscan进行探测，但从前几天开始，masscan工具也开始出现了很多误报，扫描了很多并不开放的端口，扫描命令类似这个
masscan配置：
./masscan -p 443 -iL asn/140096-ipv4 --wait=3 --rate=10000 -oL data1.txt --interface WARP
你有出现这种情况吗？抱歉，我实在不知道该在哪里讨论这个问题，希望能借用一下这个板块
