### ISSUE TITLE
The scan never ends

### ISSUE THREAD

**Issue by morpheuslord** [idealeer/xmap#14]
**The scan is running for the past 1 hour**
and estimated completion is around 130 years

**To Reproduce**
1. scanned localhost

**Screenshots**

![image](https://github.com/idealeer/xmap/assets/70637311/06beef6c-92bc-40a3-821e-91fff9cddde3)

**Desktop**
 - Kali WSL
 - Brave

**Comment by idealeer** [comment]
yes. the default scanning speed is 1pps. to increase it, you need to set up it with -R or -B option.

**Comment by morpheuslord** [comment]
ok i will try
