### ISSUE TITLE
关于periphery的发现问题。

### ISSUE THREAD

**Issue by guanyueup** [idealeer/xmap#15]
李老师您好，我想用您的xmap来发现periphery，我用的扫描参数是这样的   xmap -6 -x 64 {prefix} -R 5000 -M icmp_echo_gw -U rand --iid-num=2 -O csv --output-fields="saddr,daddr,desc,data," -o /home/zhengzhaopeng/result.csv   ，输出模块中的saddr是periphery的地址吗？如果是那应该能ping通吧？我试了ping了一个saddr地址，不能ping通。还有一个问题就是xmap可以输出扫描时的target的地址吗？我再usage里没发现有这方面的描述。希望您在不忙的时候能解答一下我的疑问，谢谢您。

**Comment by idealeer** [comment]
好的，有问题可以再讨论。saddr 是探测的地址，outersaddr 是网关地址。默认使用 `xmap -M icmp_echo_gw -h` 可以看到使用说明，`xmap -M icmp_echo_gw --list-output-field`可以看到输出的各个字段说明。
