### ISSUE TITLE
关于过滤模块的success选项

### ISSUE THREAD

**Issue by guanyueup** [idealeer/xmap#17]
李老师你好，我想问一下过滤模块的success选项是什么含义，当我设置success = 0的时候所有的输出都会不见。您在参数说明中这这样说的For example, a filter for only successful, non-duplicate responses would be written as: --output-filter="success = 1 && repeat = 0". 这个successful 是指成功收到的回应包吗？当success = 0的时候因为所有的包都是成功接收的所以就不会输出结果，我这么理解可以吗？希望您又时间的时候解答以下我的疑惑，谢谢。

**Comment by idealeer** [comment]
哈喽，是的，不同的扫描模块有不同的 success 的定义，过滤条件 success=1 是输出成功的包，反之类似。如果需要所有的包，可以选择 success=1|success=0。

**Comment by guanyueup** [comment]
您可以给我一份有关于各个success的具体定义的相关说明吗？

**Comment by idealeer** [comment]
使用 `xmap -M 模块名 -h`，可以看到各个模块的使用帮助，里面有介绍。

**Comment by guanyueup** [comment]
好的，谢谢李老师。
