### ISSUE TITLE
GCC 14 compiler error, int-conversion

### ISSUE THREAD

**Issue by xiota** [idealeer/xmap#23]
GCC 14.1.1.  Some warnings now considered errors.

```
/home/builder/build/src/xmap/src/state.c:39:36: error: initialization of ‘unsigned char’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
   39 |     .source_ip_addresses         = NULL,
```

**Comment by idealeer** [comment]
Please add "-Wint-conversion" to Line 38 of file CMakeLists.txt and try again.

**Comment by xiota** [comment]
@idealeer Are you recommending as workaround or test of potential solution?  Unless this project is discontinued, best solution would be to adjust source (add cast or other change) because future compiler releases will be more strict.

**Comment by idealeer** [comment]
thx, will do the improvement

**Comment by idealeer** [comment]
done
