### ISSUE TITLE
Missing headers `#include <sys/time.h>`

### ISSUE THREAD

**Issue by xiota** [idealeer/xmap#24]
**Describe the bug**

Arch Linux, GCC 14.2.1.  Current HEAD (15f628c) is affected.

Multiple files (`src/probe_modules/module_dns*.c`) produce errors similar to:
```
src/probe_modules/module_dnss.c:941:13: error: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  941 |             gettimeofday(&t, NULL);
      |             ^~~~~~~~~~~~
```

Adding header resolves issue.
```
#include <sys/time.h>
```

**To Reproduce**

1. Clone repo.
2. Fix [#23](https://github.com/idealeer/xmap/issues/23) by replacing `NULL` with `0` in [`src/state.c:39`](https://github.com/idealeer/xmap/blob/15f628c0d9a6e244d3088f4bd840e72b3ba1f435/src/state.c#L39).
3. Attempt to configure and build with cmake.

**Expected behavior**

Build should succeed

**Additional context**

I am comaintainer of `aur/xmap-git`.  I am adding workarounds for #23 and #24 to the package, but would prefer these be fixed upstream.

**Comment by idealeer** [comment]
tkx, will fix them shortly.

**Comment by idealeer** [comment]
done
