### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by Mr-x2020** [idealeer/xmap#5]
I get this error when compiling
![image](https://user-images.githubusercontent.com/65666323/137461617-7da43654-9aa3-4c60-8f6c-630d396b5114.png)

**Comment by z3r0err** [comment]
I have same issue with Debian 11

**Comment by idealeer** [comment]
Hi,

I'll check it.

**Comment by juergenhoetzel** [comment]
Same issue on Arch Linux (gcc 11.1.0). Opened PR [Prevent multiple definiton of global variable IID](https://github.com/idealeer/xmap/pull/7)

**Comment by z3r0err** [comment]
> Same issue on Arch Linux (gcc 11.1.0). Opened PR [Prevent multiple definiton of global variable IID](https://github.com/idealeer/xmap/pull/7)

thanks, solved for me

**Comment by idealeer** [comment]
@juergenhoetzel, cool man, I will check and merge the patch.
