### ISSUE TITLE
Non point-point IPv6 scanner

### ISSUE THREAD

**Issue by demingry** [idealeer/xmap#8]
I started a xmap instance on Azure virtual machine, Azure only provide IPv6 balance, not point to point (/128) public address, middle-ware convert. It can ping IPv6 address correctly and can be accessed via IPv6 address, but xmap does not work. I tried to capture network packets when scanning. Sniffer packet sent but no response(like www.sdu.edu.cn and www.sdwu.edu.cn, the two alive hosts I do promise I can correctly ping, but xmap cannot detect up). Alternatively, another provider, Ubuntu20 installed, with p2p IPv6 and I got public IPv6 add via `ifconfig->eth0`, but ./xmap output:

`Jan 08 08:17:48.907 [ERROR] get_gateway-linux: interface specified (eth0) does not match the interface of the default gateway (). You will need to manually specify the MAC address of your gateway.
Jan 08 08:17:48.907 [FATAL] xmap: could not detect default gateway address for eth0. Try setting default gateway mac address (-G).`

`arp -a` no record, curious.

**Comment by demingry** [comment]
tcpdump showed obviously, ping host request with response packet, however, xmap sent request but no response packet.

**Comment by idealeer** [comment]
Hi, XMap identifies the gateway MAC address by arp detection (IPv4). So if `arp -a` does not work, XMap can neither find the gateway MAC address.

To solve this issue, just set the gateway MAC address with `-G`.

**Comment by demingry** [comment]
IPv6 only, no IPv4 supported.
