### ISSUE TITLE
input ip cidr file (-w)

### ISSUE THREAD

**Issue by webr00t** [idealeer/xmap#9]
zmap accepts file input. but xmap doesn't accept it.

Is this possible ?

**Comment by idealeer** [comment]
XMap also accepts file input, plz use `-I` or `--list-of-ips-file` option.

**Comment by webr00t** [comment]
i think support only ip list ? not ip CİDR list ?

**Comment by webr00t** [comment]
> XMap also accepts file input, plz use `-I` or `--list-of-ips-file` option.

i think support only ip list ? not ip CİDR list ?

**Comment by idealeer** [comment]
Yeah, you can put either ip list or ip cidr list into --list-of-ips-file.
